// Code generated by MockGen. DO NOT EDIT.
// Source: collection.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	service "20dojo-online/pkg/server/service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCollectionServiceInterface is a mock of CollectionServiceInterface interface.
type MockCollectionServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionServiceInterfaceMockRecorder
}

// MockCollectionServiceInterfaceMockRecorder is the mock recorder for MockCollectionServiceInterface.
type MockCollectionServiceInterfaceMockRecorder struct {
	mock *MockCollectionServiceInterface
}

// NewMockCollectionServiceInterface creates a new mock instance.
func NewMockCollectionServiceInterface(ctrl *gomock.Controller) *MockCollectionServiceInterface {
	mock := &MockCollectionServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCollectionServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionServiceInterface) EXPECT() *MockCollectionServiceInterfaceMockRecorder {
	return m.recorder
}

// GetUserCollectionList mocks base method.
func (m *MockCollectionServiceInterface) GetUserCollectionList(serviceRequest *service.GetUserCollectionListRequest) (*service.GetUserCollectionListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCollectionList", serviceRequest)
	ret0, _ := ret[0].(*service.GetUserCollectionListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCollectionList indicates an expected call of GetUserCollectionList.
func (mr *MockCollectionServiceInterfaceMockRecorder) GetUserCollectionList(serviceRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCollectionList", reflect.TypeOf((*MockCollectionServiceInterface)(nil).GetUserCollectionList), serviceRequest)
}
